# Numpy Tutorial
-------------------------
* [넘파이 사이트](https://numpy.org/)

In [2]:
score = [12,34,56]

In [3]:
for i in range(3):
    score[i]+=3

In [4]:
print(score)

[15, 37, 59]


In [5]:
for i,s in enumerate(score): # 값과 인덱스를 같이 주는 함수
    score[i] = s+3
print(score)

[18, 40, 62]


In [6]:
score = list(map(lambda x:x+3, score))

In [7]:
print(score)

[21, 43, 65]


In [8]:
import numpy as np

np.__version__ #version 볼 수 있는 방법 (습관들이기) 

'1.23.1'

![](https://editor.analyticsvidhya.com/uploads/78382numpy_arrays.png)

* 머신러닝 알고리즘은 낮은 차원부터 높은 차원까지 알고리즘을 검증해 나간다
* shape를 항상 확인하며 작업하는 습관이 좋다 + type()
* 위의 자료구조들은 모두 tensor라고 부른다

## ndarray 클래스 

In [9]:
xarr = np.array([23,45,56,76])
xarr

array([23, 45, 56, 76])

In [10]:
type(xarr) #numpy.ndarray 여야만 메소드 사용가능

numpy.ndarray

In [11]:
xarr.shape #1개짜리 차원

(4,)

In [12]:
type(xarr.shape)

tuple

In [13]:
xarr.dtype #data type

#int32, int64, float32, float64 : 주로 사용하는 data type들 

dtype('int32')

In [14]:
xarr.size
# 개수

4

In [15]:
xarr.itemsize
#bit수

4

In [16]:
xarr.size * xarr.itemsize

16

In [17]:
yarr = np.array([[12,34],[56,78]])
print(yarr.shape)

yarr = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]],
                 [[9,10],[11,12]]])
yarr.shape

(2, 2)


(3, 2, 2)

In [18]:
print(yarr)
yarr

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
yarr.dtype

dtype('int32')

In [20]:
yarr.size

12

In [21]:
yarr.itemsize

4

In [22]:
yarr.dtype

dtype('int32')

In [23]:
yarr.astype('float32') #yarr = yarr.astype('float32')로 명시적으로 하지 않으면

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)

In [24]:
yarr.dtype #원본이 바뀌지 않음

dtype('int32')

In [25]:
yarr = yarr.astype('float32')

In [26]:
yarr.dtype

dtype('float32')

In [27]:
xarr = np.array([23,45,56,76], dtype='float64')
xarr.dtype
#가져올때 바꿀 수도 있으나 먼저 읽고나서 바꿔주는 것이 가독성이 좋음

dtype('float64')

In [28]:
yarr = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]],
                 [[9,10],[11,12]]])
yarr.shape
#dtype, shape은 확인하는 습관이 좋음
#shape을 맞춰줘야 기능을 사용할 수 있음

(3, 2, 2)

In [29]:
yarr = yarr.reshape(1, 3, 2, 2)
yarr.shape

(1, 3, 2, 2)

In [30]:
yarr

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [31]:
yarr = yarr.reshape(-1,3, 2, 2)
yarr.shape

(1, 3, 2, 2)

In [32]:
yarr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
yarr = yarr.reshape(-1,2,2)
# -1 내가 정해준 개수에 맞춰서 결정해줘
yarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [34]:
yarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
yarr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
yarr.reshape(-1,3,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [37]:
yarr[np.newaxis, :] #새로운 축을 생성

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [38]:
yarr.reshape(3,2,2,-1)

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]]],


       [[[ 5],
         [ 6]],

        [[ 7],
         [ 8]]],


       [[[ 9],
         [10]],

        [[11],
         [12]]]])

In [39]:
np.arange(0,10,2).reshape(-1)

array([0, 2, 4, 6, 8])

### 데이터 시각화

In [40]:
np.linspace(0,10,8) #0,10 사이를 8개로 나눠줘

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [41]:
np.full((2,3), 0)

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
yarr.shape

(3, 2, 2)

In [44]:
np.zeros_like(yarr) #똑같은 쉐잎인데 0으로 다 채워진

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

## random

In [45]:
np.random.uniform(0,10,10) #0하고 10사이에서 동일한 확률로 10개 뽑을게

array([5.5271672 , 1.80728609, 0.274423  , 3.09459914, 3.08901619,
       2.15275278, 1.94249735, 9.60198136, 1.35069446, 5.6487408 ])

In [46]:
np.random.normal(0,1,10)#정규분포 (평균, 표준편차, 뽑을 개수) 의 확률로 뽑음

array([ 1.14923859,  0.8291418 , -0.31553481, -0.92010958, -0.62411159,
        0.29263351, -0.98610506,  1.68019323,  0.53265005, -0.63078811])

In [47]:
np.random.randn(2,5) #표준정규분포 안에서 2,5형태로 만듦

array([[-0.42809079,  1.20351627, -1.01938576,  1.77386493,  0.24902707],
       [-0.45383102, -0.6080329 ,  1.11040575,  1.12577409, -0.69414336]])

## 함수

In [48]:
xarr = np.arange(12).reshape(3,4)
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
xarr.sum(axis=0) # ( ) 번째 축으로 더하기

array([12, 15, 18, 21])

In [53]:
xarr.sum(axis=1)

array([ 6, 22, 38])

In [54]:
np.sum(xarr, axis=1)

array([ 6, 22, 38])

In [56]:
xarr.mean(axis=0)

array([4., 5., 6., 7.])

In [57]:
np.mean(xarr, axis=0)

array([4., 5., 6., 7.])

In [58]:
xarr.min(axis=0)

array([0, 1, 2, 3])

In [59]:
xarr.max(axis=1)

array([ 3,  7, 11])

In [61]:
xarr + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [62]:
xarr + [3] # broadcasting

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [65]:
xarr + [3,3,3,3]

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [67]:
xarr*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [70]:
x = np.array([[1,2], [3,4]]) 
y = np.array([[1,2], [3,4]])

In [71]:
x * y #원소끼리 곱

array([[ 1,  4],
       [ 9, 16]])

In [73]:
x@y # 행렬 곱 

array([[ 7, 10],
       [15, 22]])

In [79]:
x = np.array([1,2,3]) 
y = np.array([1,2,3])

In [80]:
np.dot(x,y) #같은 위치끼리 더해서 다 더함 

14

In [83]:
x = np.array([[1,2], [3,4]]) 
y = np.array([[1,2], [3,4]])
np.dot(x,y)#2차원부터는 행렬곱처럼 동작함
# 0 부터 다차원까지 for문으로 다룰 때 편함 

array([[ 7, 10],
       [15, 22]])

In [85]:
x = np.array([[1,2], [3,4]]) 
y = np.array([[1,2], [3,4]])

np.matmul(x,y) # 행렬 곱만 시행하는 함수 

array([[ 7, 10],
       [15, 22]])

### *축과 shape, random 만드는 방법기억하기

In [91]:
x = np.array([1,4,2,3])
x > 2
#numpy의 연산은 기본적으로 원소 하나하나에 적용됨 

array([False,  True, False,  True])

### 비교연산

In [93]:
type(x > 2)

numpy.ndarray

In [96]:
x[[False,  True, False,  True]] # true에 해당하는 값만 가져오기

array([4, 3])

In [103]:
x[x>2] = -1
#원치 않는 값을 지우거나 새로운 값을 넣는 등 데이터를 손볼때

In [105]:
x

array([ 1, -1,  2, -1])

### array 합치기

In [123]:
x = np.array([1,2,3])
y = [4,5,6]
z = [7,8,9]

In [118]:
np.concatenate((x,y),axis=0)

array([1, 2, 3, 4, 5, 6])

In [120]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.hstack((x,y)) # 데이터 해더를 붙일 때

array([1, 2, 3, 4, 5, 6])

In [135]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([4,5,6,7]).reshape(2,2)
z = np.array([7,8,9])

In [144]:
np.concatenate((x,y), axis=1)

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [146]:
x = [[1,2],[3,4]]
x

[[1, 2], [3, 4]]

In [147]:
x[1][0]

3

In [164]:
x = np.array([[1,2],[3,4]]) 

In [165]:
x[1,0]
# 일반적인 배열과 다르게 접근 가능

3

In [166]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [168]:
np.where(x>3) # 3보다 큰 index를 가져옴

(array([3, 4], dtype=int64),)

In [170]:
np.where(x>3,1,0) #3보다 크면 1 3보다 작으면 0 출력

array([0, 0, 0, 1, 1])

In [175]:
x = np.array([1,2,3,4,5,6])
x = np.where(x>3, 1, 0)
x.sum() #3보다 큰 개 몇개인가? : 데이터 정리에 용이

3

In [178]:
x = np.random.randn(4,3)
x

array([[ 2.11329052, -1.20227148,  0.85439702],
       [-1.00409111, -1.10223504, -2.05386545],
       [ 0.46891411,  0.24928536, -0.80220826],
       [ 0.2233654 ,  0.6560303 , -0.67231015]])

In [180]:
np.argmax(x,axis=1) #같은 리스트 안에서 가장 큰 값을 꺼내는 함수

array([0, 0, 0, 1], dtype=int64)

In [187]:
xarr = np.array([1,2,3,4,5,6,7])
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [188]:
xarr[0:5]

array([1, 2, 3, 4, 5])

In [189]:
xarr[:-1] #데이터를 끊어줄때 많이 사용

array([1, 2, 3, 4, 5, 6])

In [190]:
xarr = np.array([1,2,3,4,5,6,7])
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [195]:
y = xarr[3:5]
y

array([4, 5])

In [199]:
y[0] = -1
y

array([-1,  5])

In [201]:
xarr #같은 레퍼런스 값을 가지고 있어서 조심해야함

array([ 1,  2,  3, -1,  5,  6,  7])

In [202]:
xarr = np.array([1,2,3,4,5,6,7])

In [210]:
y = xarr[3:5].copy() # 복사본의 레퍼런스 붙이기
y[0] = -1
#원본이 손상되지 않도록 하기 위해 copy를 해주는 것이 좋음
#한가지 데이터로 여러 알고리즘을 돌릴때 좋음

In [211]:
print(y, xarr)

[-1  5] [1 2 3 4 5 6 7]


In [221]:
iris = np.genfromtxt('./datasets/iris.csv', delimiter=',', skip_header=True)
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [218]:
iris.shape

(150, 5)

In [222]:
iris.dtype

dtype('float64')

In [227]:
xarr = iris[:,:-1] #[row조건, col조건]
xarr

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [229]:
xarr[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [236]:
xarr[:,0].mean() #1번 col의 평균

5.843333333333334

In [238]:
xarr[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [246]:
m = 5.8
x = xarr[xarr[:,0]>m,:]
y = xarr[xarr[:,0]<=m,:]

In [247]:
y[:,0].max()

5.8

In [248]:
x.shape

(70, 4)

In [249]:
y.shape

(80, 4)

In [250]:
np.savez('my_iris.npz', my_x=x, my_y=y) # file name, key
# 바이너리 형태로 압축해서 파일을 저장하기

In [251]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 36AF-C0CC

 C:\workspace\myml 디렉터리

2022-07-14  오후 02:47    <DIR>          .
2022-07-14  오전 10:01    <DIR>          ..
2022-07-14  오후 12:03    <DIR>          .ipynb_checkpoints
2022-07-14  오후 02:47            54,343 01_numpy.ipynb
2022-07-14  오후 02:23    <DIR>          datasets
2022-07-14  오후 02:47             5,302 my_iris.npz
               2개 파일              59,645 바이트
               4개 디렉터리  343,796,592,640 바이트 남음


In [253]:
my_iris = np.load('my_iris.npz') #파일 불러오기
type(my_iris)

numpy.lib.npyio.NpzFile

In [256]:
xarr = my_iris['my_x'] # key 값을 통해 불러올 수 있음 
xarr

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [6.1, 3. , 4.6, 1.4],
       [6.2, 2.9, 4.3, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3